// import 'package:flutter/widgets.dart';
// import 'package:nasa_apod_design_system/nasa_apod_design_system.dart';

// enum UKeepTextLevel {
//   bodyMedium(XTextLevel.bodyMedium),
//   bodyLarge(XTextLevel.bodyLarge),
//   titleSmall(XTextLevel.titleSmall),
//   titleMedium(XTextLevel.titleMedium),
//   titleLarge(XTextLevel.titleLarge);

//   final XTextLevel xLevel;

//   const UKeepTextLevel(this.xLevel);
// }

// class UKeepText extends XText {
//   UKeepText.(
//     String data, {
//     required UKeepTextLevel level,
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super(
//           data,
//           xLevel: level.xLevel,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const Text(
//     String data, {
//     required TextStyle style,
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.custom(
//           data,
//           style: style,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.labelSmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.labelSmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.labelMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.labelMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.labelLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.labelLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.bodySmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.bodySmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.bodyMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.bodyMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.bodyLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.bodyLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.titleSmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.titleSmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.titleMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.titleMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.titleLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.titleLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.headlineSmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.headlineSmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.headlineMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.headlineMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.headlineLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.headlineLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.displaySmall(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.displaySmall(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.displayMedium(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.displayMedium(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );

//   const UKeepText.displayLarge(
//     String data, {
//     super.key,
//     StrutStyle? strutStyle,
//     TextAlign? textAlign,
//     TextDirection? textDirection,
//     Locale? locale,
//     bool? softWrap,
//     TextOverflow? overflow,
//     int? maxLines,
//     String? semanticsLabel,
//     TextWidthBasis? textWidthBasis,
//     TextHeightBehavior? textHeightBehavior,
//     Color? selectionColor,
//     TextScaler? textScaler,
//   }) : super.displayLarge(
//           data,
//           strutStyle: strutStyle,
//           textAlign: textAlign,
//           textDirection: textDirection,
//           locale: locale,
//           softWrap: softWrap,
//           overflow: overflow,
//           maxLines: maxLines,
//           semanticsLabel: semanticsLabel,
//           textWidthBasis: textWidthBasis,
//           textHeightBehavior: textHeightBehavior,
//           selectionColor: selectionColor,
//           textScaler: textScaler,
//         );
// }
