name: nasa_apod_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.9
  nasa_apod_core:
    path: ../core
  nasa_apod_design_system:
    path: ../design_system
  url_strategy: ^0.2.0
  flutter_bloc: ^8.1.3
  timezone: ^0.9.2
  
dev_dependencies:
  build_runner: ^2.4.8
  faker: 2.0.0 #2.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.0.0
  mocktail: 0.1.4 #1.0.2
  network_image_mock: 2.0.1
  test_utils:
    path: ../test_utils

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

# build_runner:
#   scripts:
#     buildDel: dart run build_runner build --delete-conflicting-outputs
#     watchDel: dart run build_runner watch --delete-conflicting-outputs
#     watch: dart run build_runner watch