name: nasa_apod_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.5 <4.0.0"
dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.3.2
  nasa_apod_core:
    path: ../core
  nasa_apod_design_system:
    path: ../design_system
  timezone: ^0.9.2
  url_strategy: ^0.2.0
dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  mocktail: ^1.0.4
  test_utils:
    path: ../test_utils
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
