name: nasa_apod_design_system
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  # TODO(Kevin): remove this dependency, use material_toolkit instead
  gap: ^3.0.1
  nasa_apod_core:
    path: ../core
  shimmer: ^3.0.0
  sliver_tools: ^0.2.5
  # TODO(Kevin): remove this dependency, use material_toolkit instead
  tap_builder: ^0.3.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test_utils:
    path: ../test_utils

flutter:
  fonts:
    - family: apod_icons
      fonts:
        - asset: packages/nasa_apod_design_system/fonts/apod_icons.ttf
    - family: Poppins
      fonts:
        - asset: packages/nasa_apod_design_system/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: packages/nasa_apod_design_system/fonts/Poppins-Bold.ttf
          weight: 700
